sudo: false

language: go

go:
  - "1.17.x"
  - "1.16.x"
  - "1.15.x"
  - "1.14.x"
  - "1.13.x"
  - "1.x"

env:
  - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - go get -u golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-pro
  - go test -race ./...

notifications:
  email: false